from hr_little_api.functional import say, motor, close_mouth, command_list, wait_for_motors_and_speaking, \
    head_turn_middle, neutral_eyebrows, frown_eyebrows, head_turn_right, head_turn_left, poke_tounge, wait, \
    raise_eyebrows, wait_for_motors, move_robot, eye_lid_close, eye_lid_open, reset_motors
from hr_little_api.robot import Robot, MotorId, Animation
from hr_little_api.builders import MotorId, MotorCommandBuilder, SayCommandBuilder, \
    WalkCommandBuilder, MotorId, WalkDirection, WaitCommandBuilder, WaitType, CallbackCommandBuilder, CallbackType, \
    CommandListBuilder
from threading import Thread
import time
import os

import _thread
import time
robot = Robot()
robot.connect()

# Define a function for the thread


robot.do(
    #motor(MotorId.head_turn,0.5, 0.0),
    #motor(MotorId.head_pitch,1.0, 0.0),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    motor(MotorId.eyelids,0,0.1),
    print('0'),
    motor(MotorId.eyebrows,0,0.1),
    print('0'),
    
    #motor(MotorId.mouth,m,0.0),
    #motor(MotorId.lip_corners,lc, 0.0),
            )
    



